version: '3.8'

services:
  backend:
    build: .
    container_name: forms-flow-custom-services
    ports:
      - "5005:5005"
    env_file:
      - .env
    environment:
      - PORT=5005
    restart: always
